# USB port
port: /dev/serial/by-id/usb-FTDI_FT231X_USB_UART_DN0123RN-if00-port0
# Tf frame id
frame_id: imu_bosch_link
# Data reading frequency
freqency: 5
# Sensor operation mode --> modes could be found in sensor datasheet
operation_mode: 0x08
